### ISSUE TITLE
设计数据表

### ISSUE THREAD

**Issue by jianfengye** [huoding-fullstack/wiki#1]
需求描述：将前后台的数据表结构设计出来，并且仿造必要的初始化的用户数据，搭建在测试环境中
截止时间：2019-5-12
开发：轩脉刃（和所有人一起讨论）
测试：老王

**Comment by jianfengye** [comment]
https://github.com/huoding-fullstack/wiki/wiki/%E6%95%B0%E6%8D%AE%E5%BA%93%E5%AD%97%E5%85%B8

除了用户表之外的主题和评论表

**Comment by huoding** [comment]
**topics:**

- id 已经 unsigned 了，所以是 int(10)，不是 int(11)，或者是不是直接全部使用 bigint

- type 是保留关键字，不适合直接做字段名，或者是不是不应该有type，而加入 tags 功能，因为一个 topic 可能处于多个 tags，而不是某一种 type，所以是 一对多，而不是一对一

- summary不要使用text

- status 直接用字符串，不需要用int映射（虽然违反范式，但是属于实战考虑）

- create_time等改成created_at这种格式，update也是，考虑是不是加入 deleted_at 软删除功能

- zan 这种拼音命名尽可能避免

- 表编码使用 utf8mb4

- user_id 之类的外键应该放在表定义的上面，比如id字段的下面，这样更符合视觉上的美感

**comments:**

- 多级评论可能出现无法一次性取出某个 topic 所有 comments 的情况，此时现有表结构搞不定需求，需要考虑类似先根遍历树之类的方法

**topic_action:**

- 重复，应该统一一个点赞服务的表

**comment_action:**

- 重复，应该统一一个点赞服务的表

**Comment by jianfengye** [comment]
https://github.com/huoding-fullstack/wiki/blob/master/2019051121-db.md 数据表字段更新
